# Generated by Django 3.2.9 on 2021-11-19 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specialization', models.CharField(choices=[('Agriculture', 'Agriculture'), ('Automobiles', 'Automobiles'), ('Defense', 'Defense'), ('Financial', 'Financial'), ('Healthcare', 'Healthcare'), ('Manufacturing', 'Manufacturing'), ('Media', 'Media'), ('Mining', 'Mining'), ('Oil and gas', 'Oil and gas'), ('Retail', 'Retail'), ('Technology', 'Technology')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('US', 'America'), ('Malaysia', 'Malaysia'), ('Ukraine', 'Ukraine'), ('UK', 'Great Britain and Northern Ireland'), ('Kenya', 'Kenya'), ('Netherlands', 'Netherlands'), ('Canada', 'Canada'), ('Austria', 'Austria'), ('Germany', 'Germany'), ('Colombia', 'Colombia'), ('Israel', 'Israel'), ('Brazil', 'Brazil'), ('Indonesia', 'Indonesia'), ('Denmark', 'Denmark'), ('Italy', 'Italy'), ('Australia', 'Australia'), ('Greece', 'Greece'), ('Russia', 'Russian Federation'), ('Pakistan', 'Pakistan'), ('Nigeria', 'Nigeria'), ('China', 'China'), ('Poland', 'Poland'), ('Turkey', 'Turkey'), ('Japan', 'Japan'), ('Mexico', 'Mexico'), ('Sweden', 'Sweden'), ('India', 'India'), ('Philippines', 'Philippines'), ('N Korea', "The Democratic People's Republic of Korea"), ('Spain', 'Spain'), ('Ireland', 'Ireland'), ('Egypt', 'Egypt'), ('Argentina', 'Argentina'), ('S Korea', 'The Republic of Korea'), ('Iran', 'Iran'), ('France', 'French Republic'), ('Saudi Arabia', 'Saudi Arabia'), ('Syria', 'Syria'), ('NZ', 'New Zealand')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('US', 'America'), ('Malaysia', 'Malaysia'), ('Ukraine', 'Ukraine'), ('UK', 'Great Britain and Northern Ireland'), ('Kenya', 'Kenya'), ('Netherlands', 'Netherlands'), ('Canada', 'Canada'), ('Austria', 'Austria'), ('Germany', 'Germany'), ('Colombia', 'Colombia'), ('Israel', 'Israel'), ('Brazil', 'Brazil'), ('Indonesia', 'Indonesia'), ('Denmark', 'Denmark'), ('Italy', 'Italy'), ('Australia', 'Australia'), ('Greece', 'Greece'), ('Russia', 'Russian Federation'), ('Pakistan', 'Pakistan'), ('Nigeria', 'Nigeria'), ('China', 'China'), ('Poland', 'Poland'), ('Turkey', 'Turkey'), ('Japan', 'Japan'), ('Mexico', 'Mexico'), ('Sweden', 'Sweden'), ('India', 'India'), ('Philippines', 'Philippines'), ('N Korea', "The Democratic People's Republic of Korea"), ('Spain', 'Spain'), ('Ireland', 'Ireland'), ('Egypt', 'Egypt'), ('Argentina', 'Argentina'), ('S Korea', 'The Republic of Korea'), ('Iran', 'Iran'), ('France', 'French Republic'), ('Saudi Arabia', 'Saudi Arabia'), ('Syria', 'Syria'), ('NZ', 'New Zealand')], max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_regions', to='manager.country')),
            ],
        ),
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Agriculture', 'Agriculture'), ('Automobiles', 'Automobiles'), ('Defense', 'Defense'), ('Financial', 'Financial'), ('Healthcare', 'Healthcare'), ('Manufacturing', 'Manufacturing'), ('Media', 'Media'), ('Mining', 'Mining'), ('Oil and gas', 'Oil and gas'), ('Retail', 'Retail'), ('Technology', 'Technology')], max_length=50)),
                ('corporations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corp_sectors', to='manager.corporation')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_sectors', to='manager.region')),
                ('unions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='union_sectors', to='manager.union')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_parties', to='manager.country')),
            ],
        ),
        migrations.CreateModel(
            name='Paramilitary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paramilitaries', to='manager.country')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('character_name', models.CharField(max_length=255)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceo', to='manager.corporation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_accounts', to=settings.AUTH_USER_MODEL)),
                ('paramilitary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='military_leader', to='manager.paramilitary')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='manager.party')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_players', to='manager.region')),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='union_boss', to='manager.union')),
            ],
        ),
    ]
