# Generated by Django 3.2.9 on 2021-12-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20211121_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='character_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='paramilitary',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='union',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
